[tool.poetry]
name = "pycryptoarg"
version = "0.1.0"
description = ""
authors = ["Sirius Bell"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
