[project]
name = "pycrypto"
version = "0.1.0"
description="simple script to encrypt a file or message"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argparse>=1.4.0",
    "loguru>=0.7.3",
]
